language: node_js
node_js:
- 12.6.0
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- npm install -g hexo-cli
install:
- npm install
script:
- ln theme.config.yml themes/Hacker/_config.yml
- hexo generate
deploy:
  provider: script
  script: scp -o stricthostkeychecking=no -P $ServerPort -r public/* root@$ServerHost:/blog
  skip-cleanup: true
  keep-history: true
